; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.26"

; Profiles
projects[valhalla][download][type] = ""
projects[valhalla][download][url] = ""
projects[valhalla][type] = "profile"

; Modules
projects[addressfield][subdir] = "contrib"
projects[addressfield][version] = "1.0-beta4"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.2"
projects[ctools][patches][] = "ctools-fix-warning-message-1739718-32.patch"

projects[ckeditor][subdir] = "contrib"
projects[ckeditor][version] = "1.13"

projects[date][subdir] = "contrib"
projects[date][version] = "2.6"

projects[diff][subdir] = "contrib"
projects[diff][version] = "2.0"

projects[email][subdir] = "contrib"
projects[email][version] = "1.2"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.2"

projects[entityreference][subdir] = "contrib"
projects[entityreference][version] = "1.0"

projects[features][subdir] = "contrib"
projects[features][version] = "2.0"

projects[field_collection][subdir] = "contrib"
projects[field_collection][version] = "1.0-beta5"

projects[field_group][subdir] = "contrib"
projects[field_group][version] = "1.1"

projects[imce][subdir] = "contrib"
projects[imce][version] = "1.4"

projects[jquery_update][subdir] = "contrib"
projects[jquery_update][version] = "2.4"

projects[l10n_update][subdir] = "contrib"
projects[l10n_update][version] = "1.0-beta3"

projects[locationmap][subdir] = "contrib"
projects[locationmap][version] = "2.2"

projects[mailsystem][subdir] = "contrib"
projects[mailsystem][version] = "2.34"

projects[mimemail][subdir] = "contrib"
projects[mimemail][version] = "1.0-beta1"

projects[references][subdir] = "contrib"
projects[references][version] = "2.0"

projects[panels][subdir] = "contrib"
projects[panels][version] = "3.0-alpha3"

projects[role_delegation][subdir] = "contrib"
projects[role_delegation][version] = "1.1"

projects[token][subdir] = "contrib"
projects[token][version] = "1.4"

projects[views][subdir] = "contrib"
projects[views][version] = "3.5"

projects[views_data_export][subdir] = "contrib"
projects[views_data_export][version] = "3.0-beta7"

projects[valghalla][download][type] = "git"
projects[valghalla][download][url] = "git://github.com/tthbellcom/valghalla.git"
projects[valghalla][download][branch] = "feature/VALG-1_more_than_one_election"
projects[valghalla][type] = "module"

; Themes
projects[bootstrap][version] = "3.0"

projects[valghalla_bs_theme][download][type] = "git"
projects[valghalla_bs_theme][download][url] = "git://github.com/bellcom/valghalla_bs_theme.git"
projects[valghalla_bs_theme][type] = "theme"

; Libraries
libraries[ckeditor][download][type]= "get"
libraries[ckeditor][download][url] = "http://download.cksource.com/CKEditor/CKEditor/CKEditor%204.1.2/ckeditor_4.1.2_standard.zip"
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][destination] = "modules/contrib/ckeditor"
